name: Weekly Test Execution

on:
  schedule:
    - cron: '30 10 * * 0' # To run tests every Sunday at 10:30 AM UTC
  workflow_dispatch: # To trigger the workflow manually from GitHub Actions

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set up JDK 11
        uses: actions/setup-java@v3
        with:
          distribution: 'temurin'
          java-version: '11'

      - name: Install Allure
        run: |
          curl -o allure.tgz -L https://github.com/allure-framework/allure2/releases/download/2.21.0/allure-2.21.0.tgz
          tar -zxvf allure.tgz
          sudo mv allure-2.21.0 /opt/allure
          sudo ln -s /opt/allure/bin/allure /usr/local/bin/allure

      - name: Build and test with Maven
        run: mvn clean test

      - name: Generate Allure report
        run: mvn allure:report

      - name: Archive Allure Report
        uses: actions/upload-artifact@v4
        with:
          name: allure-report
          path: target/site/allure-maven-plugin

      - name: Deploy Allure Report to GitHub Pages
        if: success()
        run: |
          mkdir -p gh-pages
          cp -r target/site/allure-maven-plugin/* gh-pages/
          touch gh-pages/.nojekyll

      - name: Deploy to GitHub Pages
        uses: JamesIves/github-pages-deploy-action@v4
        with:
          branch: gh-pages
          folder: gh-pages

      - name: Archive Allure Results (ZIP)
        run: |
          zip -r allure-report.zip target/site/allure-maven-plugin

      - name: Send email with test report
        uses: dawidd6/action-send-mail@v3
        with:
          server_address: smtp.ionos.fr
          server_port: 587
          username: "dev@rolandguissony.com"
          password: "${{ secrets.EMAIL_PASSWORD }}"
          from: "GitHub Actions"
          to: "dev@rolandguissony.com"
          subject: "Test Results - Multiplication Project"
          body: "The test execution has completed successfully. You can download the Allure report from the GitHub artifacts or view it online."
          attachments: allure-report.zip
