name: Daily Test Execution - Morning and Evening

on:
  schedule:
    - cron: '0 10 * * *'
    - cron: '0 18 * * *' 
  workflow_dispatch:     

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set up JDK 11
        uses: actions/setup-java@v3
        with:
          distribution: 'temurin'
          java-version: '11'

      - name: Install Allure
        run: |
          curl -o allure.tgz -L https://github.com/allure-framework/allure2/releases/download/2.21.0/allure-2.21.0.tgz
          tar -zxvf allure.tgz
          sudo mv allure-2.21.0 /opt/allure
          sudo ln -s /opt/allure/bin/allure /usr/local/bin/allure

      - name: Create Target Directory
        run: mkdir -p target/allure-results

      - name: Build and test with Maven
        run: mvn clean test | tee target/execution-log.txt

      - name: Verify Allure Results Directory
        run: |
          if [ -z "$(ls -A target/allure-results 2>/dev/null)" ]; then
            echo "❌ Allure results directory is empty. Tests might not have generated results."
            exit 1
          fi

      - name: Generate Allure report
        run: mvn allure:report | tee -a target/execution-log.txt

      - name: Archive Execution Log
        uses: actions/upload-artifact@v4
        with:
          name: execution-log
          path: target/execution-log.txt

      - name: Archive Allure Results
        uses: actions/upload-artifact@v4
        with:
          name: allure-results
          path: target/allure-results

      - name: Archive Allure Report
        uses: actions/upload-artifact@v4
        with:
          name: allure-report
          path: target/site/allure-maven-plugin

      - name: Prepare Allure Report for Deployment
        if: success()
        run: |
          mkdir -p gh-pages
          cp -r target/site/allure-maven-plugin/* gh-pages/
          cp -r target/allure-results gh-pages/
          touch gh-pages/.nojekyll

      - name: Deploy to GitHub Pages
        uses: JamesIves/github-pages-deploy-action@v4
        with:
          branch: gh-pages
          folder: gh-pages
          token: ${{ secrets.GH_PAT }}
          clean: true

      - name: Archive Allure Results and Report (ZIP)
        run: |
          zip -r allure-report.zip target/site/allure-maven-plugin target/allure-results target/execution-log.txt

      - name: Send email with test report
        uses: dawidd6/action-send-mail@v3
        with:
          server_address: smtp.ionos.fr
          server_port: 587
          username: "dev@rolandguissony.com"
          password: "${{ secrets.EMAIL_PASSWORD }}"
          from: "GitHub Actions"
          to: "dev@rolandguissony.com"
          subject: "Test Results - Multiplication Project"
          body: "The test execution has completed successfully. You can download the Allure report from the GitHub artifacts or view it online."
          attachments: allure-report.zip
